name: TotalReview
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas=2.0.3
  - numpy=1.24.3
  - tqdm=4.66.1
  - matplotlib=3.7.2
  - scikit-learn=1.3.0
  - biopython=1.81
  - nltk=3.8.1
  - spacy=3.7.2
  - pip=23.3.1
  - pip:
    - torch==2.1.0
    - torchvision==0.16.0
    - torchaudio==2.1.0
    - transformers==4.35.0
    - datasets==2.14.5
    - huggingface_hub==0.19.4
    - accelerate==0.25.0
    - sentence-transformers==2.2.2
    - pymed==5.0.0
    - bertopic==0.15.0
    - networkx==3.1
    - pyvis==0.3.2
    - pybliometrics==3.5.0
    - rapidfuzz==3.5.2